/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as PublicPublicIdRouteImport } from './routes/public/$publicId'
import { Route as AuthTailoringIndexRouteImport } from './routes/_auth/tailoring/index'
import { Route as AuthCvIndexRouteImport } from './routes/_auth/cv/index'
import { Route as AuthTailoringJobIdRouteImport } from './routes/_auth/tailoring/$jobId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicPublicIdRoute = PublicPublicIdRouteImport.update({
  id: '/public/$publicId',
  path: '/public/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTailoringIndexRoute = AuthTailoringIndexRouteImport.update({
  id: '/tailoring/',
  path: '/tailoring/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCvIndexRoute = AuthCvIndexRouteImport.update({
  id: '/cv/',
  path: '/cv/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTailoringJobIdRoute = AuthTailoringJobIdRouteImport.update({
  id: '/tailoring/$jobId',
  path: '/tailoring/$jobId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/public/$publicId': typeof PublicPublicIdRoute
  '/tailoring/$jobId': typeof AuthTailoringJobIdRoute
  '/cv/': typeof AuthCvIndexRoute
  '/tailoring/': typeof AuthTailoringIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/public/$publicId': typeof PublicPublicIdRoute
  '/': typeof AuthIndexRoute
  '/tailoring/$jobId': typeof AuthTailoringJobIdRoute
  '/cv': typeof AuthCvIndexRoute
  '/tailoring': typeof AuthTailoringIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/public/$publicId': typeof PublicPublicIdRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/tailoring/$jobId': typeof AuthTailoringJobIdRoute
  '/_auth/cv/': typeof AuthCvIndexRoute
  '/_auth/tailoring/': typeof AuthTailoringIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/public/$publicId'
    | '/tailoring/$jobId'
    | '/cv/'
    | '/tailoring/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/public/$publicId'
    | '/'
    | '/tailoring/$jobId'
    | '/cv'
    | '/tailoring'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/public/$publicId'
    | '/_auth/'
    | '/_auth/tailoring/$jobId'
    | '/_auth/cv/'
    | '/_auth/tailoring/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PublicPublicIdRoute: typeof PublicPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/public/$publicId': {
      id: '/public/$publicId'
      path: '/public/$publicId'
      fullPath: '/public/$publicId'
      preLoaderRoute: typeof PublicPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tailoring/': {
      id: '/_auth/tailoring/'
      path: '/tailoring'
      fullPath: '/tailoring/'
      preLoaderRoute: typeof AuthTailoringIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cv/': {
      id: '/_auth/cv/'
      path: '/cv'
      fullPath: '/cv/'
      preLoaderRoute: typeof AuthCvIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tailoring/$jobId': {
      id: '/_auth/tailoring/$jobId'
      path: '/tailoring/$jobId'
      fullPath: '/tailoring/$jobId'
      preLoaderRoute: typeof AuthTailoringJobIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthTailoringJobIdRoute: typeof AuthTailoringJobIdRoute
  AuthCvIndexRoute: typeof AuthCvIndexRoute
  AuthTailoringIndexRoute: typeof AuthTailoringIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthTailoringJobIdRoute: AuthTailoringJobIdRoute,
  AuthCvIndexRoute: AuthCvIndexRoute,
  AuthTailoringIndexRoute: AuthTailoringIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PublicPublicIdRoute: PublicPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
