import { Colors } from '../../../styles/theme/colors'
import { FontFamily, FontWeight } from '../../../styles/theme/typography'
import { Spacing } from '../../../styles/theme/spacing'
import { BorderRadius } from '../../../styles/theme/radius'

export const styles = {
  hero: {
    background: Colors.gradientHeroDark,
    padding: `${Spacing.xxl} ${Spacing.lg}`,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: Spacing.lg,
    width: '100%',
    minHeight: '24rem',
  },
  headline: {
    fontFamily: FontFamily.heading,
    fontWeight: FontWeight.bold,
    fontSize: '3.2rem',
    color: Colors.white,
    margin: 0,
    textAlign: 'center' as const,
    lineHeight: 1.15,
  },
  subtitle: {
    fontSize: '1.5rem',
    color: 'rgba(255,255,255,0.75)',
    margin: 0,
    textAlign: 'center' as const,
  },
  searchBar: {
    display: 'flex',
    alignItems: 'center',
    background: Colors.white,
    borderRadius: BorderRadius.full,
    padding: `${Spacing.xs} ${Spacing.xs} ${Spacing.xs} ${Spacing.lg}`,
    gap: Spacing.xs,
    width: '100%',
    maxWidth: '72rem',
    boxShadow: '0 4px 32px rgba(0,0,0,0.25)',
  },
  inputWrapper: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  input: {
    border: 'none',
    background: 'transparent',
    fontSize: '1.4rem',
    color: Colors.textMain,
    outline: 'none',
    width: '100%',
    padding: `${Spacing.sm} 0`,
  },
  divider: {
    width: '1px',
    height: '2.4rem',
    background: Colors.surfaceBorder,
    flexShrink: 0,
  },
  icon: {
    color: Colors.textSub,
    flexShrink: 0,
    fontSize: '1.6rem',
  },
  searchBtn: {
    borderRadius: BorderRadius.full,
    border: 'none',
    background: Colors.gradientTailorBtn,
    color: Colors.white,
    fontWeight: 600,
    fontSize: '1.4rem',
    padding: `${Spacing.sm} ${Spacing.lg}`,
    cursor: 'pointer',
    flexShrink: 0,
    height: '4rem',
    whiteSpace: 'nowrap' as const,
  },
  chips: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: Spacing.sm,
    justifyContent: 'center',
  },
  chip: {
    background: 'rgba(255,255,255,0.15)',
    color: Colors.white,
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: BorderRadius.full,
    padding: `${Spacing.xs} ${Spacing.md}`,
    fontSize: '1.3rem',
    cursor: 'pointer',
    transition: 'background 0.15s',
    fontFamily: FontFamily.body,
    fontWeight: FontWeight.medium,
  },
}
